# Generated by Django 5.1.7 on 2025-12-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cities', '0001_initial'),
        ('events', '0001_initial'),
        ('gastronomie', '0002_remove_plate_destination_plate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attending_events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_destinations',
            field=models.ManyToManyField(blank=True, related_name='followers', to='cities.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_plates',
            field=models.ManyToManyField(blank=True, related_name='fans', to='gastronomie.plate'),
        ),
    ]
