# Generated by Django 5.1.7 on 2025-12-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='destination',
        ),
        migrations.AddField(
            model_name='plate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gastronomie/'),
        ),
        migrations.AddField(
            model_name='plate',
            name='restaurants',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
